{
	"array" : [
		{
			"internalId": 0,
			"gameId": 211,
			"header": "Эконом",
			"desc" : "",
			"basePrice" : 10,
			"imageId" : "auto_econom",
			"count" : 1,
			"type" : 1,
			"contains" : [6,7,8,9,10,11,12,13,14]
		},
		{
			"internalId": 1,
			"gameId": 211,
			"header": "Средний",
			"desc" : "",
			"basePrice" : 340,
			"imageId" : "auto_middle",
			"count" : 1,
			"type" : 1,
			"contains" : []
		},
		{
			"internalId": 2,
			"gameId": 211,
			"header": "Премиум",
			"desc" : "",
			"basePrice" : 10,
			"imageId" : "auto_premium",
			"count" : 1,
			"type" : 1,
			"contains" : []
		},
		{
			"internalId": 3,
			"gameId": 211,
			"header": "Мото",
			"desc" : "",
			"basePrice" : 10,
			"imageId" : "auto_moto",
			"count" : 1,
			"type" : 1,
			"contains" : []
		},
		{
			"internalId": 4,
			"gameId": 211,
			"header": "Уникальные",
			"desc" : "",
			"basePrice" : 20000,
			"imageId" : "auto_unique",
			"count" : 1,
			"type" : 1,
			"isNew" : 0,
			"contains" : []
		},
		{
			"internalId": 200,
			"gameId": 211,
			"header": "Грузовой",
			"desc" : "",
			"basePrice" : 10,
			"imageId" : "auto_gruz",
			"count" : 1,
			"type" : 1,
			"contains" : []
		},
		{
			"internalId": 412,
			"gameId": 211,
			"header": "Яхты",
			"desc" : "",
			"basePrice" : 20000,
			"imageId" : "auto_yacht",
			"count" : 1,
			"type" : 1,
			"isNew" : 0,
			"contains" : []
		},
		{
			"internalId": 5,
			"gameId": 555,
			"header": "ЗАЗ",
			"subheader" : "968M",
			"header_store": "АЗ",
			"subheader_store" : "968",
			"basePrice" : 10,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [118, 32, 2, 135],
			"isNew" : 0
		},
		{
			"internalId": 6,
			"gameId": 549,
			"header": "ВАЗ",
			"subheader" : "1111",
			"header_store": "АЗ",
			"subheader_store" : "1111",
			"desc" : "Автомобиль АЗ 1111",
			"basePrice" : 15,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [2,2],
			"specs" : [120, 24, 2, 210],
			"isNew" : 0
		},
		{
			"internalId": 7,
			"gameId": 401,
			"header": "ВАЗ",
			"subheader" : "2101",
			"header_store": "Копейка",
			"subheader_store" : "",
			"desc" : "Автомобиль Копейка",
			"basePrice" : 30,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [142, 22, 4, 325],
			"isNew" : 0
		},
		{
			"internalId": 8,
			"gameId": 479,
			"header": "ГАЗ",
			"subheader" : "Волга 2410",
			"header_store": "АЗ",
			"subheader_store" : "2410",
			"desc" : "Автомобиль АЗ 2410",
			"basePrice" : 40,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [0,0],
			"specs" : [170, 17, 4, 500],
			"isNew" : 0
		},
		{
			"internalId": 9,
			"gameId": 496,
			"header": "Volkswagen",
			"subheader" : "Golf GTI 2",
			"header_store": "Goal",
			"subheader_store" : "2",
			"desc" : "Автомобиль Goal 2",
			"basePrice" : 70,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [197, 8, 4, 380],
			"isNew" : 0
		},
		{
			"internalId": 10,
			"gameId": 404,
			"header": "ВАЗ",
			"subheader" : "2107",
			"header_store": "Семерка",
			"subheader_store" : "",
			"desc" : "Автомобиль Семерка",
			"basePrice" : 75,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [3,3],
			"specs" : [158, 17, 4, 379],
			"isNew" : 0
		},
		{
			"internalId": 11,
			"gameId": 458,
			"header": "ВАЗ",
			"subheader" : "2114",
			"header_store": "Четырка",
			"subheader_store" : "",
			"desc" : "Автомобиль Четырка",
			"basePrice" : 97,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [5,5],
			"specs" : [160, 13, 4, 427],
			"isNew" : 0
		},
		{
			"internalId": 12,
			"gameId": 585,
			"header": "ВАЗ",
			"subheader" : "2115",
			"header_store": "Пятнашка",
			"subheader_store" : "",
			"desc" : "Автомобиль Пятнашка",
			"basePrice" : 105,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [160, 13, 4, 445],
			"isNew" : 0
		},
		{
			"internalId": 13,
			"gameId": 536,
			"header": "Volvo",
			"subheader" : "242 DL",
			"header_store": "242 DL",
			"subheader_store" : "",
			"desc" : "Автомобиль 242 DL",
			"basePrice" : 125,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [176, 11, 4, 200],
			"isNew" : 0
		},
		{
			"internalId": 14,
			"gameId": 529,
			"header": "ВАЗ",
			"subheader" : "2170",
			"header_store": "АЗ",
			"subheader_store" : "2170",
			"desc" : "Автомобиль АЗ 2170",
			"basePrice" : 150,
			"count" : 1,
			"type" : 7,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [183, 11, 4, 430],
			"isNew" : 0
		},
		{
			"internalId": 17,
			"gameId": 555,
			"header": "Для вас",
			"subheader" : "968M",
			"header_store": "АЗ",
			"subheader_store" : "968",
			"basePrice" : 10,
			"salePercent" : 20,
			"count" : 1,
			"type" :0,
			"saleTime" : 1007251200,
			"rot" : [0.0, 0.0, 0.0],
			"scale" : [0.0, 0.0, 0.0],
			"colors" : [1,1],
			"specs" : [118, 32, 2, 135],
			"isNew" : 0
		},
		{
			"internalId": 332,
			"gameId": 196,
			"header": "Снегурочка",
			"subheader" : "в юбке",
			"basePrice" : 1500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 333,
			"gameId": 129,
			"header": "Шляпник",
			"subheader" : "из Алисы",
			"basePrice" : 2500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 334,
			"gameId": 130,
			"header": "Санта Клаус",
			"subheader" : "иностранец",
			"basePrice" : 2500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 335,
			"gameId": 24,
			"header": "Дед Мороз",
			"subheader" : "отечественный",
			"basePrice" : 2500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 340,
			"gameId": 197,
			"header": "Девочка-кролик",
			"subheader" : "обычная",
			"basePrice" : 2500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 336,
			"gameId": 245,
			"header": "Снегурочка",
			"subheader" : "внучка Деда",
			"basePrice" : 2500,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		},
		{
			"internalId": 337,
			"gameId": 243,
			"header": "Снегурочка",
			"subheader" : "молодежная",
			"basePrice" : 3000,
			"imageId" : "image_test",
			"count" : 1,
			"type" : 2,
			"isNew" : 0
		}
		
	]
}